### ISSUE TITLE
Make the cloning script more generic

### ISSUE THREAD

**Issue by TjWallas** [TjWallas/sandnet-migration-strategies#21]
* We would like to invoke the script to clone a container by name. Therefore, the script should take a container name to clone as argument. Also, the destination container name as a second argument. 

* We need to double check if containers preserve their IP / MAC addresses or not after cloning and then use pipework to adjust them like the cloned container accordingly.

* One important thing to note is the line which has `ls.... ` in it. We need to record and save the exact container hash from prodnet after the checkpoint has been created. That hash variable could then be used instead of the `ls...` hack when starting the container from a checkpoint on the sandnet.

More info:
* Getting a container's hash ( https://stackoverflow.com/questions/34496882/get-docker-container-id-from-container-name )
```
sudo docker ps -aqf "name=containername"
```

**Comment by JeannineBorn** [comment]
@TjWallas: liveCloning.sh takes two parameters containername and cloned containername. 
for ex.: `./liveClone.sh db db_sand` 

But i'm currently stuck in line 96: `ssh -o StrictHostKeyChecking=no -i /home/vagrant/.ssh/prodsand vagrant@192.168.0.3 'sudo docker start --checkpoint-dir=/home/vagrant/checkpoints/'$container_hash'/checkpoints --checkpoint=check1 "$container_sand"'`

No matter how i change the command, i always get the error: 
> error during connect: Post /v1.30/containers/start?checkpoint=check1&checkpoint-dir=%2Fhome%2Fvagrant%2Fcheckpoints%2F2c84b53677dbdf2a031827a1341f4802d927f6e293afd918ec82382bbbef3045%2Fcheckpoints: unexpected redirect in response

**Comment by TjWallas** [comment]
@JeannineBorn Try replacing `'$container_hash'` with `"$container_hash"`. The above command appears to have mixed double quotes and single quotes. You either need to escape them properly (i.e. `"a double quote \"enclosed\""`) or be mindful of what the quoted string boundaries are :)
