### ISSUE TITLE
Perform thread synchronization so that the threads wait for one vote to go through and be measured.

### ISSUE THREAD

**Issue by TjWallas** [TjWallas/sandnet-migration-strategies#28]
* We need to guarantee that the voting thread will wait until the result thread picks up a change in the number of votes (difference is **exactly one**) before sending the next vote

* We also need to guarantee that the result thread will wait for the vote thread to vote before picking up the result.

The algorithm could roughly work as follows:
```
result_picked_up = True

def send_vote():
    while True:
        if result_picked_up:
            result_picked_up = False
            recordTimestamp1()
            sendVoteHTTPRequest()
        
        time.sleep(0.2)

def get_votes():
    while True:
        if not result_picked_up:
            ConnectToSocketIO and wait for 20ms
            Receive message and parse it
            Verify that votes increased by one
            recordTimestamp2()
            result_picked_up = True

        time.sleep(0.2)


def main():
    Thread(target=send_vote).start()
    Thread(target=get_votes).start()
```

You can also use already existing lock primitives and atomic operations in python if you want to:
https://docs.python.org/2/library/threading.html#lock-objects

**Comment by TjWallas** [comment]
@JeannineBorn I actually recommend using an actual atomic lock compared to the above algorithm because the above algorithm is not synchronization safe. If one thread is faster than the other, two iterations could occur and the vote could be at that time incremented by 2 or 3 instead of 1.

**Comment by TjWallas** [comment]
@JeannineBorn Just found you a nice tutorial for python thread synchronization: https://hackernoon.com/synchronization-primitives-in-python-564f89fee732?gi=2154aebfaedc

**Comment by JeannineBorn** [comment]
@TjWallas: Thread synchronization works but it takes a significant longer time for the vote to be processed.
time without lock is:
![votewithoutlock](https://user-images.githubusercontent.com/11292639/41710084-14588f78-7545-11e8-9765-841732f18c99.png)
and time with lock is:
![votewithlock](https://user-images.githubusercontent.com/11292639/41710102-24d5e31e-7545-11e8-88c5-2308cd1c7b5a.png)
