### ISSUE TITLE
Measuring throughput before, and after cloning

### ISSUE THREAD

**Issue by TjWallas** [TjWallas/sandnet-migration-strategies#36]
Repeat the same process in #35 except that instead of ping, we'd like to measure the TCP and UDP throughput using `iperf`.

More info:
https://www.linode.com/docs/networking/diagnostics/install-iperf-to-diagnose-network-speed-in-linux/

**Comment by JeannineBorn** [comment]
- [x] create Dockerfiles with Entrypoints 
- [x] iperf client connects to iperfserver
- [x] the server is livecloned prior to the client
- [ ] iperf command continues to execute in sandnet
- [ ] netcat started in sandnet has to be redirected to the host or sandnet itself

**Comment by JeannineBorn** [comment]
@TjWallas : after the migration, iperfclient stops the command and does not resume it in sandnet.
when executing `docker logs iperfclient_clone` in sandnet, i get the message 

> nc: Polling Error: Interrupted system call

so instead of standard error message 

> Connection Refused

it crashes completely.
How can i stop it from crashing?

**Comment by JeannineBorn** [comment]
issue was resolved when using ncat instead of nc

**Comment by JeannineBorn** [comment]
@TjWallas: when stopping the containers in prodnet, i noticed that iperfclient started in sandnet still has some issues.
from the log i get: 

> libnsock nsock_trace_handler_callback(): Callback: READ ERROR [Connection reset by peer (104)] for EID 18 [192.168.0.4:1447]
Ncat: Connection reset by peer.

the client seems to receive an RST flag, which stops it.
Is setting an iptables rule that drops RST the right solution to this?

**Comment by TjWallas** [comment]
@JeannineBorn No. You should not set up an iptables rule for this. TCP should handle itself ^,^

I need more info to be able to help. It looks from the above that the error is rather related to the netcat we use to pipe the results, not iperf. No?

* Is the netcat server on 192.168.0.4 still running?
* You can also set up the netcat client to re-connect on errors: https://unix.stackexchange.com/questions/432249/nc-to-retry-on-connection-refuse

**Comment by JeannineBorn** [comment]
executing the command `iperf -p 1344 -t 50 -i 1 -c 174.15.1.6 | ncat -vvv 192.168.0.4 1447` in container iperfclient_clone in sandnet gives the output:

> Ncat: Version 7.40 ( https://nmap.org/ncat )
NCAT DEBUG: Using system default trusted CA certificates and those in /usr/share/ncat/ca-bundle.crt.
NCAT DEBUG: Unable to load trusted CA certificates from /usr/share/ncat/ca-bundle.crt: error:02001002:system library:fopen:No such file or directory
libnsock nsock_iod_new2(): nsock_iod_new (IOD #1)
libnsock nsock_connect_tcp(): TCP connection requested to 192.168.0.4:1447 (IOD #1) EID 8
libnsock nsock_trace_handler_callback(): Callback: CONNECT ERROR [Connection refused (111)] for EID 8 [192.168.0.4:1447]

when exiting an restarting `ncat -l -p 1447` in extnet, iperf command in sandnet executes correctly.

**Comment by TjWallas** [comment]
@JeannineBorn Why do you need to manually start iperf on the cloned container? Isn't iperf migrated "live" already?

**Comment by JeannineBorn** [comment]
@TjWallas: i started iperf manually on sandnet to test if ncat server in extnet is reachable, which it wasn't.

As you can see here, ncat in extnet receives output until try 16, after that, live-cloning of the container iperfclient1 begins
![iperf](https://user-images.githubusercontent.com/11292639/43537585-ff1f7fa4-95bf-11e8-8769-8545852f9a1d.png)
when iperfclient1 is migrated live as iperfclient_clone, there is no output in extnet.
`docker logs iperfclient_clone` gives the above mentioned error 

> libnsock nsock_trace_handler_callback(): Callback: READ ERROR [Connection reset by peer (104)] for EID 18 [192.168.0.4:1447]
Ncat: Connection reset by peer.

That's when i started the command from iperfclient_clone manually to see whether i would get output in extnet. This also only left me with an error message, but this time with additional information:

> Ncat: Version 7.40 ( https://nmap.org/ncat )
NCAT DEBUG: Using system default trusted CA certificates and those in /usr/share/ncat/ca-bundle.crt.
NCAT DEBUG: Unable to load trusted CA certificates from /usr/share/ncat/ca-bundle.crt: error:02001002:system library:fopen:No such file or directory
libnsock nsock_iod_new2(): nsock_iod_new (IOD #1)
libnsock nsock_connect_tcp(): TCP connection requested to 192.168.0.4:1447 (IOD #1) EID 8
libnsock nsock_trace_handler_callback(): Callback: CONNECT ERROR [Connection refused (111)] for EID 8 [192.168.0.4:1447]

**Comment by TjWallas** [comment]
@JeannineBorn Now that we can only rely on writing the output to files instead of netcat, you can fall back to cloning instead of migration :). (i.e. `--leave-running=True`)
