### ISSUE TITLE
Clone a simple ping container using CRIU

### ISSUE THREAD

**Issue by TjWallas** [TjWallas/sandnet-migration-strategies#47]
TODO: Wallas

**Comment by TjWallas** [comment]
Relevant:
* https://www.redhat.com/en/blog/how-can-process-snapshotrestore-help-save-your-day?source=onsite&key=about
* https://criu.org/What_cannot_be_checkpointed

**Comment by TjWallas** [comment]
Also relevant: https://criu.org/External_bind_mounts

**Comment by TjWallas** [comment]
As CRIU cannot checkpoint Sockets other than TCP, UDP, UNIX, packet and netlink, and..
As ping uses INET sockets (See: https://lwn.net/Articles/422330/ ). A ping container cannot be check pointed.

**Comment by TjWallas** [comment]
Sadly most of the existing tools use INET raw sockets for ICMP. This includes nping as well. But, we can use `httping` which opens a TCP stream socket or DGRAM socket for UDP accordingly :)

So, instead of the ping containers, we should use `httping`.

Here is a sample run. On prodnet:

```
sudo docker network create --subnet 174.15.1.0/24 -d ovs mynet || true
docker run -d --name httping --network mynet --ip 174.15.1.11 bretfisher/httping https://www.google.com
/vagrant/liveCloning.sh httping httping_clone
# CONGRATULATIONS! IT WORKS =)
```

Handing this issue back to you @JeannineBorn . Please replace all ping containers with httping. Of course you would need an internal container that runs a simple http server or so ad adjust the target of httping above accordingly. Here is a way to create a simple minimal HTTP server using the lovely netcat (**Which is cloneable because it uses TCP sockets by the way!**)

**Comment by TjWallas** [comment]
@JeannineBorn The right command for a simple basic http server is as follows:
```
while true; do ( echo -ne "HTTP/1.0 200 OK\r\n\r\n"; echo;) | nc -l 1337; done
```

**Comment by JeannineBorn** [comment]
when executing the command `while true; do ( echo -ne "HTTP/1.0 200 OK\r\n\r\n"; echo;) | nc -w 2 -l 0.0.0.0 -p $PORT; done` in container ping2 that is started with `docker run --ip 182.158.0.2 -e PORT=1339 --network pingbridge -d --name ping2 busybox sleep 1000` i still get the error message 

> short read during receiving reply-headers from host 

I tried changing the Dockerfile to 

> FROM debian:jessie
RUN apt-get update
RUN apt-get install -y httping
ENTRYPOINT ["httping","-c","5"]
CMD ["182.158.0.2:1339"]

but the error message stays the same
